### ISSUE TITLE
WAVE2 Support?

### ISSUE THREAD

**Issue by Harvie** [michar71/Open-DSO-150#42]
What about this new two channel device?
https://jyetech.com/wave2-2-channel-portable-oscilloscope/

![image](https://user-images.githubusercontent.com/276504/69505474-670a6900-0f2a-11ea-8a2c-f945bab917ad.png)

Not only it has two analog channels, but at the bottom there are some pins which look like they can be used for digital inputs. At least few of them. Checked the schematics and most of them are not suitable, but some are.

**Comment by michar71** [comment]
Just found that (Because I finally have some time to work through the bug list...).
They split up the Acquisition/UI part from the UI controls by using two processors but it all looks overly complicated... (Schematic is on their webpage...)

With a few simple things they could have improved DSO-150 a lot:
- Connect USB
- Use SPI for Display
- Don't connect Buttons to Display Control Lines
- Add second analog channel

Or go to a STM32F4 ($5 instead of $1.80...). But two processors? Argghh....

(I'll work on DSO150 instead, maybe overclock processor and do a few other improvements....)

**Comment by Harvie** [comment]
> But two processors? Argghh....

Do you think you can open KiCAD and implement these improvements? :-)
